volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$db_pass
      - MYSQL_PASSWORD=$db_pass
      - MYSQL_DATABASE=$db_name
      - MYSQL_USER=$db_user

  app:
    image: nextcloud
    container_name: nextcloud
    # command: apache-foreground
    restart: always
    ports:
      - 8081:80
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=$admin_name
      - NEXTCLOUD_ADMIN_PASSWORD=$admin_pass
      - MYSQL_PASSWORD=$db_pass
      - MYSQL_DATABASE=$db_name
      - MYSQL_USER=$db_user
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      # - NEXTCLOUD_TRUSTED_DOMAINS=$trust_domain
      # - NEXTCLOUD_TRUSTED_PROXIES=$trust_proxie
      # - NEXTCLOUD_DOMAIN=$domain
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
